package com.nulabinc.zxcvbn.matchers;

import java.util.HashMap;
import java.util.Map;

public class Keyboard {
    public static final Map<String, Map<Character, String[]>> ADJACENCY_GRAPHS = new HashMap<>();
    static {
        Map<Character, String[]> qwerty = new HashMap<>();
        qwerty.put('$', new String[]{ "3#", null, null, "5%", "rR", "eE" });
        qwerty.put('(', new String[]{ "8*", null, null, "0)", "oO", "iI" });
        qwerty.put(',', new String[]{ "mM", "kK", "lL", ".>", null, null });
        qwerty.put('0', new String[]{ "9(", null, null, "-_", "pP", "oO" });
        qwerty.put('4', new String[]{ "3#", null, null, "5%", "rR", "eE" });
        qwerty.put('8', new String[]{ "7&", null, null, "9(", "iI", "uU" });
        qwerty.put('<', new String[]{ "mM", "kK", "lL", ".>", null, null });
        qwerty.put('@', new String[]{ "1!", null, null, "3#", "wW", "qQ" });
        qwerty.put('D', new String[]{ "sS", "eE", "rR", "fF", "cC", "xX" });
        qwerty.put('H', new String[]{ "gG", "yY", "uU", "jJ", "nN", "bB" });
        qwerty.put('L', new String[]{ "kK", "oO", "pP", ";:", ".>", ",<" });
        qwerty.put('P', new String[]{ "oO", "0)", "-_", "[{", ";:", "lL" });
        qwerty.put('T', new String[]{ "rR", "5%", "6^", "yY", "gG", "fF" });
        qwerty.put('X', new String[]{ "zZ", "sS", "dD", "cC", null, null });
        qwerty.put('\\', new String[]{ "]}", null, null, null, null, null });
        qwerty.put('`', new String[]{ null, null, null, "1!", null, null });
        qwerty.put('d', new String[]{ "sS", "eE", "rR", "fF", "cC", "xX" });
        qwerty.put('h', new String[]{ "gG", "yY", "uU", "jJ", "nN", "bB" });
        qwerty.put('l', new String[]{ "kK", "oO", "pP", ";:", ".>", ",<" });
        qwerty.put('p', new String[]{ "oO", "0)", "-_", "[{", ";:", "lL" });
        qwerty.put('t', new String[]{ "rR", "5%", "6^", "yY", "gG", "fF" });
        qwerty.put('x', new String[]{ "zZ", "sS", "dD", "cC", null, null });
        qwerty.put('|', new String[]{ "]}", null, null, null, null, null });
        qwerty.put('#', new String[]{ "2@", null, null, "4$", "eE", "wW" });
        qwerty.put('\'', new String[]{ ";:", "[{", "]}", null, null, "/?" });
        qwerty.put('+', new String[]{ "-_", null, null, null, "]}", "[{" });
        qwerty.put('/', new String[]{ ".>", ";:", "'\"", null, null, null });
        qwerty.put('3', new String[]{ "2@", null, null, "4$", "eE", "wW" });
        qwerty.put('7', new String[]{ "6^", null, null, "8*", "uU", "yY" });
        qwerty.put(';', new String[]{ "lL", "pP", "[{", "'\"", "/?", ".>" });
        qwerty.put('?', new String[]{ ".>", ";:", "'\"", null, null, null });
        qwerty.put('C', new String[]{ "xX", "dD", "fF", "vV", null, null });
        qwerty.put('G', new String[]{ "fF", "tT", "yY", "hH", "bB", "vV" });
        qwerty.put('K', new String[]{ "jJ", "iI", "oO", "lL", ",<", "mM" });
        qwerty.put('O', new String[]{ "iI", "9(", "0)", "pP", "lL", "kK" });
        qwerty.put('S', new String[]{ "aA", "wW", "eE", "dD", "xX", "zZ" });
        qwerty.put('W', new String[]{ "qQ", "2@", "3#", "eE", "sS", "aA" });
        qwerty.put('[', new String[]{ "pP", "-_", "=+", "]}", "'\"", ";:" });
        qwerty.put('_', new String[]{ "0)", null, null, "=+", "[{", "pP" });
        qwerty.put('c', new String[]{ "xX", "dD", "fF", "vV", null, null });
        qwerty.put('g', new String[]{ "fF", "tT", "yY", "hH", "bB", "vV" });
        qwerty.put('k', new String[]{ "jJ", "iI", "oO", "lL", ",<", "mM" });
        qwerty.put('o', new String[]{ "iI", "9(", "0)", "pP", "lL", "kK" });
        qwerty.put('s', new String[]{ "aA", "wW", "eE", "dD", "xX", "zZ" });
        qwerty.put('w', new String[]{ "qQ", "2@", "3#", "eE", "sS", "aA" });
        qwerty.put('{', new String[]{ "pP", "-_", "=+", "]}", "'\"", ";:" });
        qwerty.put('\"', new String[]{ ";:", "[{", "]}", null, null, "/?" });
        qwerty.put('&', new String[]{ "6^", null, null, "8*", "uU", "yY" });
        qwerty.put('*', new String[]{ "7&", null, null, "9(", "iI", "uU" });
        qwerty.put('.', new String[]{ ",<", "lL", ";:", "/?", null, null });
        qwerty.put('2', new String[]{ "1!", null, null, "3#", "wW", "qQ" });
        qwerty.put('6', new String[]{ "5%", null, null, "7&", "yY", "tT" });
        qwerty.put(':', new String[]{ "lL", "pP", "[{", "'\"", "/?", ".>" });
        qwerty.put('>', new String[]{ ",<", "lL", ";:", "/?", null, null });
        qwerty.put('B', new String[]{ "vV", "gG", "hH", "nN", null, null });
        qwerty.put('F', new String[]{ "dD", "rR", "tT", "gG", "vV", "cC" });
        qwerty.put('J', new String[]{ "hH", "uU", "iI", "kK", "mM", "nN" });
        qwerty.put('N', new String[]{ "bB", "hH", "jJ", "mM", null, null });
        qwerty.put('R', new String[]{ "eE", "4$", "5%", "tT", "fF", "dD" });
        qwerty.put('V', new String[]{ "cC", "fF", "gG", "bB", null, null });
        qwerty.put('Z', new String[]{ null, "aA", "sS", "xX", null, null });
        qwerty.put('^', new String[]{ "5%", null, null, "7&", "yY", "tT" });
        qwerty.put('b', new String[]{ "vV", "gG", "hH", "nN", null, null });
        qwerty.put('f', new String[]{ "dD", "rR", "tT", "gG", "vV", "cC" });
        qwerty.put('j', new String[]{ "hH", "uU", "iI", "kK", "mM", "nN" });
        qwerty.put('n', new String[]{ "bB", "hH", "jJ", "mM", null, null });
        qwerty.put('r', new String[]{ "eE", "4$", "5%", "tT", "fF", "dD" });
        qwerty.put('v', new String[]{ "cC", "fF", "gG", "bB", null, null });
        qwerty.put('z', new String[]{ null, "aA", "sS", "xX", null, null });
        qwerty.put('~', new String[]{ null, null, null, "1!", null, null });
        qwerty.put('!', new String[]{ "`~", null, null, "2@", "qQ", null });
        qwerty.put('%', new String[]{ "4$", null, null, "6^", "tT", "rR" });
        qwerty.put(')', new String[]{ "9(", null, null, "-_", "pP", "oO" });
        qwerty.put('-', new String[]{ "0)", null, null, "=+", "[{", "pP" });
        qwerty.put('1', new String[]{ "`~", null, null, "2@", "qQ", null });
        qwerty.put('5', new String[]{ "4$", null, null, "6^", "tT", "rR" });
        qwerty.put('9', new String[]{ "8*", null, null, "0)", "oO", "iI" });
        qwerty.put('=', new String[]{ "-_", null, null, null, "]}", "[{" });
        qwerty.put('A', new String[]{ null, "qQ", "wW", "sS", "zZ", null });
        qwerty.put('E', new String[]{ "wW", "3#", "4$", "rR", "dD", "sS" });
        qwerty.put('I', new String[]{ "uU", "8*", "9(", "oO", "kK", "jJ" });
        qwerty.put('M', new String[]{ "nN", "jJ", "kK", ",<", null, null });
        qwerty.put('Q', new String[]{ null, "1!", "2@", "wW", "aA", null });
        qwerty.put('U', new String[]{ "yY", "7&", "8*", "iI", "jJ", "hH" });
        qwerty.put('Y', new String[]{ "tT", "6^", "7&", "uU", "hH", "gG" });
        qwerty.put(']', new String[]{ "[{", "=+", null, "\\|", null, "'\"" });
        qwerty.put('a', new String[]{ null, "qQ", "wW", "sS", "zZ", null });
        qwerty.put('e', new String[]{ "wW", "3#", "4$", "rR", "dD", "sS" });
        qwerty.put('i', new String[]{ "uU", "8*", "9(", "oO", "kK", "jJ" });
        qwerty.put('m', new String[]{ "nN", "jJ", "kK", ",<", null, null });
        qwerty.put('q', new String[]{ null, "1!", "2@", "wW", "aA", null });
        qwerty.put('u', new String[]{ "yY", "7&", "8*", "iI", "jJ", "hH" });
        qwerty.put('y', new String[]{ "tT", "6^", "7&", "uU", "hH", "gG" });
        qwerty.put('}', new String[]{ "[{", "=+", null, "\\|", null, "'\"" });
        ADJACENCY_GRAPHS.put("qwerty", qwerty);
        Map<Character, String[]> dvorak = new HashMap<>();
        dvorak.put('$', new String[]{ "3#", null, null, "5%", "pP", ".>" });
        dvorak.put('(', new String[]{ "8*", null, null, "0)", "rR", "cC" });
        dvorak.put(',', new String[]{ "'\"", "2@", "3#", ".>", "oO", "aA" });
        dvorak.put('0', new String[]{ "9(", null, null, "[{", "lL", "rR" });
        dvorak.put('4', new String[]{ "3#", null, null, "5%", "pP", ".>" });
        dvorak.put('8', new String[]{ "7&", null, null, "9(", "cC", "gG" });
        dvorak.put('<', new String[]{ "'\"", "2@", "3#", ".>", "oO", "aA" });
        dvorak.put('@', new String[]{ "1!", null, null, "3#", ",<", "'\"" });
        dvorak.put('D', new String[]{ "iI", "fF", "gG", "hH", "bB", "xX" });
        dvorak.put('H', new String[]{ "dD", "gG", "cC", "tT", "mM", "bB" });
        dvorak.put('L', new String[]{ "rR", "0)", "[{", "/?", "sS", "nN" });
        dvorak.put('P', new String[]{ ".>", "4$", "5%", "yY", "uU", "eE" });
        dvorak.put('T', new String[]{ "hH", "cC", "rR", "nN", "wW", "mM" });
        dvorak.put('X', new String[]{ "kK", "iI", "dD", "bB", null, null });
        dvorak.put('\\', new String[]{ "=+", null, null, null, null, null });
        dvorak.put('`', new String[]{ null, null, null, "1!", null, null });
        dvorak.put('d', new String[]{ "iI", "fF", "gG", "hH", "bB", "xX" });
        dvorak.put('h', new String[]{ "dD", "gG", "cC", "tT", "mM", "bB" });
        dvorak.put('l', new String[]{ "rR", "0)", "[{", "/?", "sS", "nN" });
        dvorak.put('p', new String[]{ ".>", "4$", "5%", "yY", "uU", "eE" });
        dvorak.put('t', new String[]{ "hH", "cC", "rR", "nN", "wW", "mM" });
        dvorak.put('x', new String[]{ "kK", "iI", "dD", "bB", null, null });
        dvorak.put('|', new String[]{ "=+", null, null, null, null, null });
        dvorak.put('#', new String[]{ "2@", null, null, "4$", ".>", ",<" });
        dvorak.put('\'', new String[]{ null, "1!", "2@", ",<", "aA", null });
        dvorak.put('+', new String[]{ "/?", "]}", null, "\\|", null, "-_" });
        dvorak.put('/', new String[]{ "lL", "[{", "]}", "=+", "-_", "sS" });
        dvorak.put('3', new String[]{ "2@", null, null, "4$", ".>", ",<" });
        dvorak.put('7', new String[]{ "6^", null, null, "8*", "gG", "fF" });
        dvorak.put(';', new String[]{ null, "aA", "oO", "qQ", null, null });
        dvorak.put('?', new String[]{ "lL", "[{", "]}", "=+", "-_", "sS" });
        dvorak.put('C', new String[]{ "gG", "8*", "9(", "rR", "tT", "hH" });
        dvorak.put('G', new String[]{ "fF", "7&", "8*", "cC", "hH", "dD" });
        dvorak.put('K', new String[]{ "jJ", "uU", "iI", "xX", null, null });
        dvorak.put('O', new String[]{ "aA", ",<", ".>", "eE", "qQ", ";:" });
        dvorak.put('S', new String[]{ "nN", "lL", "/?", "-_", "zZ", "vV" });
        dvorak.put('W', new String[]{ "mM", "tT", "nN", "vV", null, null });
        dvorak.put('[', new String[]{ "0)", null, null, "]}", "/?", "lL" });
        dvorak.put('_', new String[]{ "sS", "/?", "=+", null, null, "zZ" });
        dvorak.put('c', new String[]{ "gG", "8*", "9(", "rR", "tT", "hH" });
        dvorak.put('g', new String[]{ "fF", "7&", "8*", "cC", "hH", "dD" });
        dvorak.put('k', new String[]{ "jJ", "uU", "iI", "xX", null, null });
        dvorak.put('o', new String[]{ "aA", ",<", ".>", "eE", "qQ", ";:" });
        dvorak.put('s', new String[]{ "nN", "lL", "/?", "-_", "zZ", "vV" });
        dvorak.put('w', new String[]{ "mM", "tT", "nN", "vV", null, null });
        dvorak.put('{', new String[]{ "0)", null, null, "]}", "/?", "lL" });
        dvorak.put('\"', new String[]{ null, "1!", "2@", ",<", "aA", null });
        dvorak.put('&', new String[]{ "6^", null, null, "8*", "gG", "fF" });
        dvorak.put('*', new String[]{ "7&", null, null, "9(", "cC", "gG" });
        dvorak.put('.', new String[]{ ",<", "3#", "4$", "pP", "eE", "oO" });
        dvorak.put('2', new String[]{ "1!", null, null, "3#", ",<", "'\"" });
        dvorak.put('6', new String[]{ "5%", null, null, "7&", "fF", "yY" });
        dvorak.put(':', new String[]{ null, "aA", "oO", "qQ", null, null });
        dvorak.put('>', new String[]{ ",<", "3#", "4$", "pP", "eE", "oO" });
        dvorak.put('B', new String[]{ "xX", "dD", "hH", "mM", null, null });
        dvorak.put('F', new String[]{ "yY", "6^", "7&", "gG", "dD", "iI" });
        dvorak.put('J', new String[]{ "qQ", "eE", "uU", "kK", null, null });
        dvorak.put('N', new String[]{ "tT", "rR", "lL", "sS", "vV", "wW" });
        dvorak.put('R', new String[]{ "cC", "9(", "0)", "lL", "nN", "tT" });
        dvorak.put('V', new String[]{ "wW", "nN", "sS", "zZ", null, null });
        dvorak.put('Z', new String[]{ "vV", "sS", "-_", null, null, null });
        dvorak.put('^', new String[]{ "5%", null, null, "7&", "fF", "yY" });
        dvorak.put('b', new String[]{ "xX", "dD", "hH", "mM", null, null });
        dvorak.put('f', new String[]{ "yY", "6^", "7&", "gG", "dD", "iI" });
        dvorak.put('j', new String[]{ "qQ", "eE", "uU", "kK", null, null });
        dvorak.put('n', new String[]{ "tT", "rR", "lL", "sS", "vV", "wW" });
        dvorak.put('r', new String[]{ "cC", "9(", "0)", "lL", "nN", "tT" });
        dvorak.put('v', new String[]{ "wW", "nN", "sS", "zZ", null, null });
        dvorak.put('z', new String[]{ "vV", "sS", "-_", null, null, null });
        dvorak.put('~', new String[]{ null, null, null, "1!", null, null });
        dvorak.put('!', new String[]{ "`~", null, null, "2@", "'\"", null });
        dvorak.put('%', new String[]{ "4$", null, null, "6^", "yY", "pP" });
        dvorak.put(')', new String[]{ "9(", null, null, "[{", "lL", "rR" });
        dvorak.put('-', new String[]{ "sS", "/?", "=+", null, null, "zZ" });
        dvorak.put('1', new String[]{ "`~", null, null, "2@", "'\"", null });
        dvorak.put('5', new String[]{ "4$", null, null, "6^", "yY", "pP" });
        dvorak.put('9', new String[]{ "8*", null, null, "0)", "rR", "cC" });
        dvorak.put('=', new String[]{ "/?", "]}", null, "\\|", null, "-_" });
        dvorak.put('A', new String[]{ null, "'\"", ",<", "oO", ";:", null });
        dvorak.put('E', new String[]{ "oO", ".>", "pP", "uU", "jJ", "qQ" });
        dvorak.put('I', new String[]{ "uU", "yY", "fF", "dD", "xX", "kK" });
        dvorak.put('M', new String[]{ "bB", "hH", "tT", "wW", null, null });
        dvorak.put('Q', new String[]{ ";:", "oO", "eE", "jJ", null, null });
        dvorak.put('U', new String[]{ "eE", "pP", "yY", "iI", "kK", "jJ" });
        dvorak.put('Y', new String[]{ "pP", "5%", "6^", "fF", "iI", "uU" });
        dvorak.put(']', new String[]{ "[{", null, null, null, "=+", "/?" });
        dvorak.put('a', new String[]{ null, "'\"", ",<", "oO", ";:", null });
        dvorak.put('e', new String[]{ "oO", ".>", "pP", "uU", "jJ", "qQ" });
        dvorak.put('i', new String[]{ "uU", "yY", "fF", "dD", "xX", "kK" });
        dvorak.put('m', new String[]{ "bB", "hH", "tT", "wW", null, null });
        dvorak.put('q', new String[]{ ";:", "oO", "eE", "jJ", null, null });
        dvorak.put('u', new String[]{ "eE", "pP", "yY", "iI", "kK", "jJ" });
        dvorak.put('y', new String[]{ "pP", "5%", "6^", "fF", "iI", "uU" });
        dvorak.put('}', new String[]{ "[{", null, null, null, "=+", "/?" });
        ADJACENCY_GRAPHS.put("dvorak", dvorak);
        Map<Character, String[]> jis = new HashMap<>();
        jis.put('$', new String[]{ "3#", null, null, "5%", "rR", "eE" });
        jis.put('(', new String[]{ "7'", null, null, "9)", "iI", "uU" });
        jis.put(',', new String[]{ "mM", "kK", "lL", ".>", null, null });
        jis.put('0', new String[]{ "9)", null, null, "-=", "pP", "oO" });
        jis.put('4', new String[]{ "3#", null, null, "5%", "rR", "eE" });
        jis.put('8', new String[]{ "7'", null, null, "9)", "iI", "uU" });
        jis.put('<', new String[]{ "mM", "kK", "lL", ".>", null, null });
        jis.put('@', new String[]{ "pP", "-=", null, "[{", ":*", ";+" });
        jis.put('D', new String[]{ "sS", "eE", "rR", "fF", "cC", "xX" });
        jis.put('H', new String[]{ "gG", "yY", "uU", "jJ", "nN", "bB" });
        jis.put('L', new String[]{ "kK", "oO", "pP", ";+", ".>", ",<" });
        jis.put('P', new String[]{ "oO", "00", "-=", "@`", ";+", "lL" });
        jis.put('T', new String[]{ "rR", "5%", "6&", "yY", "gG", "fF" });
        jis.put('X', new String[]{ "zZ", "sS", "dD", "cC", null, null });
        jis.put('\\', new String[]{ "^~", null, null, null, null, null });
        jis.put('`', new String[]{ null, null, null, "1!", null, null });
        jis.put('d', new String[]{ "sS", "eE", "rR", "fF", "cC", "xX" });
        jis.put('h', new String[]{ "gG", "yY", "uU", "jJ", "nN", "bB" });
        jis.put('l', new String[]{ "kK", "oO", "pP", ";+", ".>", ",<" });
        jis.put('p', new String[]{ "oO", "00", "-=", "@`", ";+", "lL" });
        jis.put('t', new String[]{ "rR", "5%", "6&", "yY", "gG", "fF" });
        jis.put('x', new String[]{ "zZ", "sS", "dD", "cC", null, null });
        jis.put('|', new String[]{ "^~", null, null, null, null, null });
        jis.put('#', new String[]{ "2\"", null, null, "4$", "eE", "wW" });
        jis.put('\'', new String[]{ "6&", null, null, "8(", "uU", "yY" });
        jis.put('+', new String[]{ "lL", "pP", "@`", ":*", "/?", ".>" });
        jis.put('/', new String[]{ ".>", ";+", ":*", null, null, null });
        jis.put('3', new String[]{ "2\"", null, null, "4$", "eE", "wW" });
        jis.put('7', new String[]{ "6&", null, null, "8(", "uU", "yY" });
        jis.put(';', new String[]{ "lL", "pP", "@`", ":*", "/?", ".>" });
        jis.put('?', new String[]{ ".>", ";+", ":*", null, null, null });
        jis.put('C', new String[]{ "xX", "dD", "fF", "vV", null, null });
        jis.put('G', new String[]{ "fF", "tT", "yY", "hH", "bB", "vV" });
        jis.put('K', new String[]{ "jJ", "iI", "oO", "lL", ",<", "mM" });
        jis.put('O', new String[]{ "iI", "9)", "00", "pP", "lL", "kK" });
        jis.put('S', new String[]{ "aA", "wW", "eE", "dD", "xX", "zZ" });
        jis.put('W', new String[]{ "qQ", "2\"", "3#", "eE", "sS", "aA" });
        jis.put('[', new String[]{ "@`", null, "^~", null, "]}", ":*" });
        jis.put('c', new String[]{ "xX", "dD", "fF", "vV", null, null });
        jis.put('g', new String[]{ "fF", "tT", "yY", "hH", "bB", "vV" });
        jis.put('k', new String[]{ "jJ", "iI", "oO", "lL", ",<", "mM" });
        jis.put('o', new String[]{ "iI", "9)", "00", "pP", "lL", "kK" });
        jis.put('s', new String[]{ "aA", "wW", "eE", "dD", "xX", "zZ" });
        jis.put('w', new String[]{ "qQ", "2\"", "3#", "eE", "sS", "aA" });
        jis.put('{', new String[]{ "@`", null, "^~", null, "]}", ":*" });
        jis.put('\"', new String[]{ "1!", null, null, "3#", "wW", "qQ" });
        jis.put('&', new String[]{ "5%", null, null, "7'", "yY", "tT" });
        jis.put('*', new String[]{ ";+", "@`", "[{", "]}", null, "/?" });
        jis.put('.', new String[]{ ",<", "lL", ";+", "/?", null, null });
        jis.put('2', new String[]{ "1!", null, null, "3#", "wW", "qQ" });
        jis.put('6', new String[]{ "5%", null, null, "7'", "yY", "tT" });
        jis.put(':', new String[]{ ";+", "@`", "[{", "]}", null, "/?" });
        jis.put('>', new String[]{ ",<", "lL", ";+", "/?", null, null });
        jis.put('B', new String[]{ "vV", "gG", "hH", "nN", null, null });
        jis.put('F', new String[]{ "dD", "rR", "tT", "gG", "vV", "cC" });
        jis.put('J', new String[]{ "hH", "uU", "iI", "kK", "mM", "nN" });
        jis.put('N', new String[]{ "bB", "hH", "jJ", "mM", null, null });
        jis.put('R', new String[]{ "eE", "4$", "5%", "tT", "fF", "dD" });
        jis.put('V', new String[]{ "cC", "fF", "gG", "bB", null, null });
        jis.put('Z', new String[]{ null, "aA", "sS", "xX", null, null });
        jis.put('^', new String[]{ null, null, null, "\\|", null, "[{" });
        jis.put('b', new String[]{ "vV", "gG", "hH", "nN", null, null });
        jis.put('f', new String[]{ "dD", "rR", "tT", "gG", "vV", "cC" });
        jis.put('j', new String[]{ "hH", "uU", "iI", "kK", "mM", "nN" });
        jis.put('n', new String[]{ "bB", "hH", "jJ", "mM", null, null });
        jis.put('r', new String[]{ "eE", "4$", "5%", "tT", "fF", "dD" });
        jis.put('v', new String[]{ "cC", "fF", "gG", "bB", null, null });
        jis.put('z', new String[]{ null, "aA", "sS", "xX", null, null });
        jis.put('~', new String[]{ null, null, null, "\\|", null, "[{" });
        jis.put('!', new String[]{ "`~", null, null, "2\"", "qQ", null });
        jis.put('%', new String[]{ "4$", null, null, "6&", "tT", "rR" });
        jis.put(')', new String[]{ "8(", null, null, "00", "oO", "iI" });
        jis.put('-', new String[]{ "00", null, null, null, "@`", "pP" });
        jis.put('1', new String[]{ "`~", null, null, "2\"", "qQ", null });
        jis.put('5', new String[]{ "4$", null, null, "6&", "tT", "rR" });
        jis.put('9', new String[]{ "8(", null, null, "00", "oO", "iI" });
        jis.put('=', new String[]{ "00", null, null, null, "@`", "pP" });
        jis.put('A', new String[]{ null, "qQ", "wW", "sS", "zZ", null });
        jis.put('E', new String[]{ "wW", "3#", "4$", "rR", "dD", "sS" });
        jis.put('I', new String[]{ "uU", "8(", "9)", "oO", "kK", "jJ" });
        jis.put('M', new String[]{ "nN", "jJ", "kK", ",<", null, null });
        jis.put('Q', new String[]{ null, "1!", "2\"", "wW", "aA", null });
        jis.put('U', new String[]{ "yY", "7'", "8(", "iI", "jJ", "hH" });
        jis.put('Y', new String[]{ "tT", "6&", "7'", "uU", "hH", "gG" });
        jis.put(']', new String[]{ ":*", "[{", null, null, null, null });
        jis.put('a', new String[]{ null, "qQ", "wW", "sS", "zZ", null });
        jis.put('e', new String[]{ "wW", "3#", "4$", "rR", "dD", "sS" });
        jis.put('i', new String[]{ "uU", "8(", "9)", "oO", "kK", "jJ" });
        jis.put('m', new String[]{ "nN", "jJ", "kK", ",<", null, null });
        jis.put('q', new String[]{ null, "1!", "2\"", "wW", "aA", null });
        jis.put('u', new String[]{ "yY", "7'", "8(", "iI", "jJ", "hH" });
        jis.put('y', new String[]{ "tT", "6&", "7'", "uU", "hH", "gG" });
        jis.put('}', new String[]{ ":*", "[{", null, null, null, null });
        ADJACENCY_GRAPHS.put("jis", jis);
        Map<Character, String[]> keypad = new HashMap<>();
        keypad.put('+', new String[]{ "9", "*", "-", null, null, null, null, "6" });
        keypad.put('*', new String[]{ "/", null, null, null, "-", "+", "9", "8" });
        keypad.put('-', new String[]{ "*", null, null, null, null, null, "+", "9" });
        keypad.put('/', new String[]{ null, null, null, null, "*", "9", "8", "7" });
        keypad.put('.', new String[]{ "0", "2", "3", null, null, null, null, null });
        keypad.put('1', new String[]{ null, null, "4", "5", "2", "0", null, null });
        keypad.put('0', new String[]{ null, "1", "2", "3", ".", null, null, null });
        keypad.put('3', new String[]{ "2", "5", "6", null, null, null, ".", "0" });
        keypad.put('2', new String[]{ "1", "4", "5", "6", "3", ".", "0", null });
        keypad.put('5', new String[]{ "4", "7", "8", "9", "6", "3", "2", "1" });
        keypad.put('4', new String[]{ null, null, "7", "8", "5", "2", "1", null });
        keypad.put('7', new String[]{ null, null, null, "/", "8", "5", "4", null });
        keypad.put('6', new String[]{ "5", "8", "9", "+", null, null, "3", "2" });
        keypad.put('9', new String[]{ "8", "/", "*", "-", "+", null, "6", "5" });
        keypad.put('8', new String[]{ "7", null, "/", "*", "9", "6", "5", "4" });
        ADJACENCY_GRAPHS.put("keypad", keypad);
        Map<Character, String[]> mac_keypad = new HashMap<>();
        mac_keypad.put('+', new String[]{ "6", "9", "-", null, null, null, null, "3" });
        mac_keypad.put('*', new String[]{ "/", null, null, null, null, null, "-", "9" });
        mac_keypad.put('-', new String[]{ "9", "/", "*", null, null, null, "+", "6" });
        mac_keypad.put('/', new String[]{ "=", null, null, null, "*", "-", "9", "8" });
        mac_keypad.put('.', new String[]{ "0", "2", "3", null, null, null, null, null });
        mac_keypad.put('1', new String[]{ null, null, "4", "5", "2", "0", null, null });
        mac_keypad.put('0', new String[]{ null, "1", "2", "3", ".", null, null, null });
        mac_keypad.put('3', new String[]{ "2", "5", "6", "+", null, null, ".", "0" });
        mac_keypad.put('2', new String[]{ "1", "4", "5", "6", "3", ".", "0", null });
        mac_keypad.put('5', new String[]{ "4", "7", "8", "9", "6", "3", "2", "1" });
        mac_keypad.put('4', new String[]{ null, null, "7", "8", "5", "2", "1", null });
        mac_keypad.put('7', new String[]{ null, null, null, "=", "8", "5", "4", null });
        mac_keypad.put('6', new String[]{ "5", "8", "9", "-", "+", null, "3", "2" });
        mac_keypad.put('9', new String[]{ "8", "=", "/", "*", "-", "+", "6", "5" });
        mac_keypad.put('8', new String[]{ "7", null, "=", "/", "9", "6", "5", "4" });
        mac_keypad.put('=', new String[]{ null, null, null, null, "/", "9", "8", "7" });
        ADJACENCY_GRAPHS.put("mac_keypad", mac_keypad);
    }
}
